# Generated by Django 2.2.5 on 2019-10-03 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FreeDay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('free_day_type', models.CharField(choices=[(1, 'Отпуск'), (2, 'Праздники'), (3, 'Отгул')], default=1, max_length=50)),
            ],
        ),
    ]
