# Generated by Django 2.2.5 on 2019-10-03 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_freeday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freeday',
            name='free_day_type',
            field=models.CharField(choices=[('Отпуск', 'Отпуск'), ('Праздники', 'Праздники'), ('Отгул', 'Отгул')], default=1, max_length=50),
        ),
    ]
