# Generated by Django 2.2.5 on 2019-10-07 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_auto_20191003_1330'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='settings',
            name='address',
        ),
        migrations.RemoveField(
            model_name='settings',
            name='messengers',
        ),
        migrations.RemoveField(
            model_name='settings',
            name='phone',
        ),
        migrations.AlterField(
            model_name='settings',
            name='additional_info',
            field=models.TextField(blank=True),
        ),
    ]
