# Generated by Django 2.2.6 on 2019-10-26 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0004_auto_20191007_1244'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointmenttime',
            options={'ordering': ['time']},
        ),
    ]
