# Generated by Django 2.2.5 on 2019-10-03 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_freeday'),
    ]

    operations = [
        migrations.AddField(
            model_name='freeday',
            name='free_day_type',
            field=models.CharField(choices=[(1, 'Отпуск'), (2, 'Праздники'), (3, 'Отгул')], default=1, max_length=50),
        ),
    ]
