# Generated by Django 2.2.5 on 2019-10-08 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0004_delete_freeday'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='created_session',
            field=models.TextField(default='One-Off'),
            preserve_default=False,
        ),
    ]
