# Generated by Django 2.2.6 on 2019-10-26 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0005_appointment_created_session'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={'ordering': ['-time']},
        ),
    ]
