# Generated by Django 2.2.6 on 2019-10-26 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-created', 'title']},
        ),
    ]
